### ISSUE TITLE
Only part of element symbol is displayed

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#357]
Only part of element symbol is displayed  in 'Labels' mode when reading CIF or RES file

Reported by: @annulen

**Comment by apienk** [comment]
The bug is still there. Here: "Ca" displayed as "a". This happens for any element with two-character symbol. Strangely enough, when full element name is selected, "Fluorine" is displayed correctly, but "alcium" instead of "Calcium". Latest GIT build.
![screenshot-20200430155852](https://user-images.githubusercontent.com/9961826/80719293-8cb02580-8afb-11ea-9fb1-85e91d120973.png)
